/**
 * esbuild.config.js — Bundle abtars into a single ESM output.
 *
 * Produces bundle/ with code-split chunks. Native addons (better-sqlite3)
 * and browser automation (patchright) are external.
 *
 * Usage: node esbuild.config.js
 */

import esbuild from "esbuild";
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Capability registry plugin ──────────────────────────────────────────────
// Generates a static import map so capabilities don't need readdirSync at runtime.

function capabilityRegistryPlugin() {
  return {
    name: "capability-registry",
    setup(build) {
      const capsDir = join(__dirname, "src", "capabilities");
      const entries = [];

      for (const dir of readdirSync(capsDir, { withFileTypes: true })) {
        if (!dir.isDirectory()) continue;
        const manifestPath = join(capsDir, dir.name, "capability.json");
        if (!existsSync(manifestPath)) continue;
        const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
        entries.push({ dir: dir.name, name: manifest.name });
      }

      const registryPath = join(capsDir, "_registry.generated.ts");
      const lines = [
        "// AUTO-GENERATED by esbuild.config.js — do not edit",
        "// Static capability registry for bundled builds",
        "",
        ...entries.map((e, i) => `import * as cap${i} from "./${e.dir}/index.js";`),
        "",
        `export const capabilities = [`,
        ...entries.map((e, i) => `  { name: ${JSON.stringify(e.name)}, module: cap${i} },`),
        "];",
        "",
      ];
      writeFileSync(registryPath, lines.join("\n"));
    },
  };
}

// ── Build ───────────────────────────────────────────────────────────────────

const external = [
  "better-sqlite3",
  "patchright",
];

const result = await esbuild.build({
  entryPoints: {
    abtars: "src/main.ts",
    "abtars-cli": "src/cli/abtars.ts",
    "abtars-browser": "src/cli/abtars-browser.ts",
    "abtars-restart": "src/cli/commands/restart.ts",
    "abtars-tweet": "src/cli/abtars-tweet.ts",
  },
  bundle: true,
  platform: "node",
  format: "esm",
  outdir: "bundle",
  splitting: true,
  external,
  banner: {
    js: [
      `import { createRequire as __bundleCreateRequire } from 'node:module';`,
      `import { fileURLToPath as __bundleFileURLToPath } from 'node:url';`,
      `import { dirname as __bundleDirname } from 'node:path';`,
      `const require = __bundleCreateRequire(import.meta.url);`,
      `const __chunk_filename = __bundleFileURLToPath(import.meta.url);`,
      `const __chunk_dirname = __bundleDirname(__chunk_filename);`,
    ].join(" "),
  },
  define: {
    "process.env.NODE_ENV": '"production"',
    "__filename": "__chunk_filename",
    "__dirname": "__chunk_dirname",
  },
  plugins: [capabilityRegistryPlugin()],
  sourcemap: true,
  minify: false,
  metafile: true,
  logLevel: "info",
});

// Write metafile for analysis
mkdirSync("bundle", { recursive: true });
writeFileSync("bundle/meta.json", JSON.stringify(result.metafile, null, 2));

const outputs = Object.keys(result.metafile.outputs);
const totalBytes = Object.values(result.metafile.outputs).reduce((sum, o) => sum + o.bytes, 0);
console.log(`\n✓ Bundle: ${outputs.length} files, ${(totalBytes / 1024 / 1024).toFixed(1)}MB total`);
