// AUTO-GENERATED by esbuild.config.js — do not edit
// Static capability registry for bundled builds

import * as cap0 from "./hotskills/index.js";
import * as cap1 from "./sleep/index.js";

export const capabilities = [
  { name: "hotskills", module: cap0 },
  { name: "sleep", module: cap1 },
];
