import { createHash } from "node:crypto";
import type Database from "better-sqlite3";
import { logWarn, logInfo } from "./logger.js";

const TAG = "embedding-provider";

/**
 * Local-only embedding generation using @xenova/transformers (optional dependency).
 *
 * If the package is not installed, the provider stays in a not-ready state
 * and embed() throws so callers (VectorIndex) can catch and skip gracefully.
 * Embeddings are cached in SQLite keyed by SHA-256 hash of the source text.
 */
export class EmbeddingProvider {
  private pipeline: any = null;
  private readonly modelName: string;

  constructor(modelName?: string) {
    this.modelName = modelName ?? "Xenova/all-MiniLM-L6-v2";
  }

  /** Load the ONNX model. Call once at startup. */
  async initialize(): Promise<void> {
    try {
      // @ts-ignore — optional dependency, may not be installed
      const transformers = await import("@xenova/transformers");
      const pipelineFn =
        typeof transformers.pipeline === "function"
          ? transformers.pipeline
          : (transformers as any).default?.pipeline;

      if (!pipelineFn) {
        logWarn(TAG, "Could not find pipeline function in @xenova/transformers");
        return;
      }

      this.pipeline = await pipelineFn("feature-extraction", this.modelName);
      logInfo(TAG, `Embedding model loaded: ${this.modelName}`);
    } catch (err) {
      logWarn(TAG, `@xenova/transformers not available — vector search disabled`);
      this.pipeline = null;
    }
  }

  /**
   * Generate an embedding vector for the given text.
   *
   * 1. Compute SHA-256 hash of text
   * 2. Check embeddings cache in SQLite
   * 3. If cached, deserialize Buffer → Float32Array and return
   * 4. If not cached, compute embedding via pipeline
   * 5. Store in cache with message_id = NULL (linked later by VectorIndex.index())
   * 6. Return the Float32Array
   */
  async embed(text: string, db: Database.Database): Promise<Float32Array> {
    if (!this.pipeline) {
      throw new Error("Embedding model not loaded");
    }

    const contentHash = createHash("sha256").update(text).digest("hex");

    // Check cache
    const cached = db
      .prepare("SELECT vector FROM embeddings WHERE content_hash = ?")
      .get(contentHash) as { vector: Buffer } | undefined;

    if (cached) {
      return new Float32Array(new Uint8Array(cached.vector).buffer);
    }

    // Compute embedding
    const output = await this.pipeline(text, { pooling: "mean", normalize: true });
    const vector: Float32Array = output.data instanceof Float32Array
      ? output.data
      : new Float32Array(output.data);

    // Store in cache (message_id is NULL — linked when VectorIndex.index() is called)
    const buffer = Buffer.from(vector.buffer);
    db.prepare(
      "INSERT OR REPLACE INTO embeddings (content_hash, message_id, vector, model_version) VALUES (?, NULL, ?, ?)",
    ).run(contentHash, buffer, this.modelName);

    return vector;
  }

  /** Check if the model is loaded and ready. */
  get isReady(): boolean {
    return this.pipeline !== null;
  }

  /** Get the current model name/version identifier. */
  get modelVersion(): string {
    return this.modelName;
  }

  /**
   * Detect if the configured model differs from the stored model version.
   * Returns true if any embedding in the DB was generated by a different model.
   */
  detectModelChange(db: Database.Database): boolean {
    const row = db
      .prepare(
        "SELECT 1 FROM embeddings WHERE model_version IS NOT NULL AND model_version != ? LIMIT 1",
      )
      .get(this.modelName) as { 1: number } | undefined;
    return row !== undefined;
  }

  /**
   * Re-generate all embeddings that were created by a different model version.
   * Looks up original text from the messages table, re-embeds with the current model,
   * and updates each row in-place. Embeddings without a linked message (e.g. ingested
   * document chunks with message_id = NULL) are skipped since the original text
   * cannot be recovered.
   *
   * Existing embeddings continue to serve queries until each row is individually updated,
   * so there is no search downtime during re-embedding.
   */
  async reembed(params: {
    db: Database.Database;
    onProgress: (processed: number, total: number) => void;
  }): Promise<void> {
    const { db, onProgress } = params;

    if (!this.pipeline) {
      throw new Error("Embedding model not loaded");
    }

    // Find all stale embeddings that have a linked message we can re-derive text from
    const staleRows = db
      .prepare(
        `SELECT e.content_hash, m.content
         FROM embeddings e
         JOIN messages m ON m.id = e.message_id
         WHERE e.message_id IS NOT NULL
           AND (e.model_version IS NULL OR e.model_version != ?)`,
      )
      .all(this.modelName) as Array<{ content_hash: string; content: string }>;

    const total = staleRows.length;
    if (total === 0) {
      onProgress(0, 0);
      return;
    }

    const updateStmt = db.prepare(
      `UPDATE embeddings SET vector = ?, model_version = ? WHERE content_hash = ?`,
    );

    for (let i = 0; i < staleRows.length; i++) {
      const row = staleRows[i]!;

      // Generate new embedding with current model
      const output = await this.pipeline(row.content, { pooling: "mean", normalize: true });
      const vector: Float32Array =
        output.data instanceof Float32Array ? output.data : new Float32Array(output.data);
      const buffer = Buffer.from(vector.buffer);

      // Update in-place — the row continues serving queries until this UPDATE commits
      updateStmt.run(buffer, this.modelName, row.content_hash);

      onProgress(i + 1, total);
    }
  }

}
