import { logAndSwallow } from "./log-and-swallow.js";
import { getEnv } from "./env-schema.js";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { logInfo, logDebug, logWarn } from "./logger.js";
import { abtarsHome } from "../paths.js";
import { loadUsers, buildUsersBlock } from "./user-registry.js";
import type { MemoryManager } from "abmind";

const TAG = "soul-loader";
const HOST_CORE_DIR = join(abtarsHome(), "core");

/** Read a single file, return empty string on failure. */
function readOr(path: string): string {
  try { return existsSync(path) ? readFileSync(path, "utf-8").trim() : ""; } catch { return ""; }
}

/** Build env-gated model behavior directives. Generated at session start. */
function buildModelInstructions(): string {
  const lines: string[] = [];
  if (getEnv().primingModelTopics) {
    lines.push("End each response with [TOPICS: kw1, kw2, kw3] — your top 3 topics from this exchange. Keep them English, lowercase, concise.");
  }
  return lines.length > 0 ? `# Model Instructions\n\n${lines.join("\n")}` : "";
}

/**
 * Build the session injection bundle: abmind 4 + host 2.
 *
 * abmind files via memory.getSessionBundle() (SOUL, profile, notes, memory-tools).
 * Transition fallback: if memory unavailable or file missing, reads from ~/.abtars/core/.
 * Host files (core_facts.md, skills_catalog.md) always from ~/.abtars/core/.
 * Appends [USERS] block.
 */
export function loadSoulBundle(memory?: MemoryManager | null): string | null {
  const parts: string[] = [];

  // abmind 4 — prefer getSessionBundle(), fall back to host core dir
  let bundle: { soul: string; profile: string; notes: string; memoryTools: string; coreFacts: string } | null = null;
  try { bundle = memory?.getSessionBundle() ?? null; } catch (err) { logAndSwallow("soul_loader", "op", err); }

  const soul = bundle?.soul || readOr(join(HOST_CORE_DIR, "SOUL.md"));
  const profile = bundle?.profile || readOr(join(HOST_CORE_DIR, "user_profile.md"));
  const notes = bundle?.notes || readOr(join(HOST_CORE_DIR, "agent_notes.md"));
  const memoryTools = bundle?.memoryTools || readOr(join(HOST_CORE_DIR, "TOOLS.md"));
  const coreFacts = bundle?.coreFacts || readOr(join(HOST_CORE_DIR, "core_facts.md"));

  if (soul) parts.push(soul);
  if (memoryTools) parts.push(memoryTools);
  if (profile) parts.push(profile);
  if (notes) parts.push(notes);
  if (coreFacts) parts.push(coreFacts);

  // Host 2 — skills_catalog stays in ~/.abtars/core/ (generated by hotskills watcher)
  const skillsCatalog = readOr(join(HOST_CORE_DIR, "skills_catalog.md"));
  if (skillsCatalog) parts.push(skillsCatalog);

  // Host 3: model-instructions — env-gated dynamic directives
  const modelInstructions = buildModelInstructions();
  if (modelInstructions) parts.push(modelInstructions);

  // [EMOTIONAL CONTEXT] — topic arcs for tone awareness
  try {
    const arcs = memory?.getEmotionalArcs() ?? [];
    if (arcs.length > 0) {
      const ARC_LABELS: Record<string, string> = { "↑": "user sentiment improving", "↓": "user sentiment worsening — be careful", "↕": "volatile — user feelings fluctuate", "→": "stable" };
      const lines = arcs.map(a => `- ${a.topic}: ${a.arc} (${ARC_LABELS[a.arc] ?? "unknown"})`);
      parts.push(`[EMOTIONAL CONTEXT]\n${lines.join("\n")}`);
    }
  } catch (err) { logAndSwallow("soul_loader", "op", err); }

  // [USERS] block
  try {
    const registry = loadUsers();
    if (registry.users.length > 0) parts.push(buildUsersBlock(registry));
  } catch (err) { logAndSwallow("soul_loader", "op", err); }

  // Current date/time — prevents model from hallucinating temporal context
  const now = new Date();
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  parts.push(`[CURRENT TIME] ${now.toLocaleDateString("en-GB")} ${days[now.getDay()]}, ${now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`);

  if (parts.length === 0) {
    logWarn(TAG, "No session bundle files found");
    return null;
  }

  logInfo(TAG, `Session bundle: ${parts.length} parts (abmind: ${bundle ? "API" : "fallback"})`);
  logDebug(TAG, `Bundle parts: soul=${!!soul} profile=${!!profile} notes=${!!notes} memTools=${!!memoryTools} coreFacts=${!!coreFacts} skills=${!!skillsCatalog}`);
  return parts.join("\n\n---\n\n");
}

/**
 * Minimal soul for Code sessions (#658): agent_notes + memory-tools + skills + time.
 * No personality, no user_profile, no core_facts, no emotional context.
 */
export function loadMinimalSoul(memory?: MemoryManager | null): string | null {
  const parts: string[] = [];

  let bundle: { notes: string; memoryTools: string } | null = null;
  try { bundle = memory?.getSessionBundle() ?? null; } catch (err) { logAndSwallow("soul_loader", "op", err); }

  const notes = bundle?.notes || readOr(join(HOST_CORE_DIR, "agent_notes.md"));
  const memoryTools = bundle?.memoryTools || readOr(join(HOST_CORE_DIR, "TOOLS.md"));

  if (notes) parts.push(notes);
  if (memoryTools) parts.push(memoryTools);

  const skillsCatalog = readOr(join(HOST_CORE_DIR, "skills_catalog.md"));
  if (skillsCatalog) parts.push(skillsCatalog);

  const now = new Date();
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  parts.push(`[CURRENT TIME] ${now.toLocaleDateString("en-GB")} ${days[now.getDay()]}, ${now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}`);

  if (parts.length === 0) return null;
  logInfo(TAG, `Minimal soul (Code): ${parts.length} parts`);
  return parts.join("\n\n---\n\n");
}
